### ISSUE TITLE
Failed to join: Member has conflicting node ID

### ISSUE THREAD

**Issue by jojonarte** [manubuhay/node_IfAlive#1]
I'm using dockerized consul agents and servers, version 0.8.1, and I'm also using terraform to manage the infrastructure

Whenever I'm relaunching (destory+create) a machine, or simply reboot it, the consul agent fails to rejoin the cluster with this error:

* Failed to join 10.136.60.53: Member 'abee16f194f7' has conflicting node ID 'a343daqw-asdr432s-qz9s340' with this agent's ID
The consul servers show the corresponding error:

 2017/05/24 13:32:43 [INFO] consul.fsm: EnsureRegistration failed: failed inserting node: node ID "a343daqw-asdr432s-qz9s340" for node "abee16f194f7" aliases existing node "a343daqw"
I tried everything the mailing list suggests:

use randomly generated node-id
use a constant unique node-id
delete the agent's data dir
force leave the failing/missing nodes
use disable host node id
Nothing. Works.

Lastly I downgraded to 0.7.5 (where uniqueness is not enforced) and the agent was able to rejoin the cluster. What are my options?

**Comment by manubuhay** [comment]
eff you

**Comment by manubuhay** [comment]
Yes sir, please buy cheap soap and eat it.
